title: Post prueba	
date: 2021-02-05
author: Jorge Portilla
email: athan.phi@outlook.com
description:Archivo creado para mi primer blog
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
_config.yml: 
theme: minima
title: Post prueba	
date: 2021-02-05
